//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealHomes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealHomes.StringConstants", typeof(StringConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.
        /// </summary>
        public static string APP_MODE {
            get {
                return ResourceManager.GetString("APP_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to najm_us_sahar@nanosofttek.com.
        /// </summary>
        public static string COMPANY_EMAIL {
            get {
                return ResourceManager.GetString("COMPANY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar-AE.
        /// </summary>
        public static string CURRENCY_CULTURE {
            get {
                return ResourceManager.GetString("CURRENCY_CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED.
        /// </summary>
        public static string CURRENCY_SYMBOL {
            get {
                return ResourceManager.GetString("CURRENCY_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUserName.
        /// </summary>
        public static string CURRENT_USER_NAME {
            get {
                return ResourceManager.GetString("CURRENT_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUser.
        /// </summary>
        public static string CURRENT_USER_OBJECT {
            get {
                return ResourceManager.GetString("CURRENT_USER_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RHSearchSearcher.
        /// </summary>
        public static string EXMINE_SEARCHER_NAME {
            get {
                return ResourceManager.GetString("EXMINE_SEARCHER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery/.
        /// </summary>
        public static string GALLERY_FOLDER_NAME {
            get {
                return ResourceManager.GetString("GALLERY_FOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/.
        /// </summary>
        public static string HOME_ADDRESS_UAE {
            get {
                return ResourceManager.GetString("HOME_ADDRESS_UAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/.
        /// </summary>
        public static string IMAGE_PATH {
            get {
                return ResourceManager.GetString("IMAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string LOGIN_FAILURE_MSG {
            get {
                return ResourceManager.GetString("LOGIN_FAILURE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500000000.
        /// </summary>
        public static string MAXSELLPRICE {
            get {
                return ResourceManager.GetString("MAXSELLPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Partials/.
        /// </summary>
        public static string PARTIAL_VIEW_PATH {
            get {
                return ResourceManager.GetString("PARTIAL_VIEW_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thumbnails/.
        /// </summary>
        public static string THUMBNAIL_FOLDER_NAME {
            get {
                return ResourceManager.GetString("THUMBNAIL_FOLDER_NAME", resourceCulture);
            }
        }
    }
}
